### ISSUE TITLE
Update runtime to org.freedesktop.Platform//24.08

### ISSUE THREAD

**Issue by devurandom** [flathub/chat.revolt.RevoltDesktop#15]
`chat.revolt.RevoltDesktop` still depends on `org.freedesktop.Platform//22.08`, cf. https://github.com/flathub/chat.revolt.RevoltDesktop/blob/b8b30e77cd41bd804c2ed23af750e70183febf69/chat.revolt.RevoltDesktop.yaml#L2-L3

**Comment by LegitGreenBoi** [comment]
It'd be nice to have this as 22.08 seems to have hit EOL recently.

**Comment by RayJW** [comment]
This was fixed and should be closed.
